export class Category {
    id: string;     //unique string generated by LB
    parentId: number;
    name: string;

    constructor(values: Object = {}){
        Object.assign(this, values);
    }
}
