import { Stock } from "./stock";
import { SelectColor } from "./selectColor";
import { FileObject } from "./fileobject";
import { ShippingInfo } from "./shippinginfo";
import { CartItem } from "./cartitem";

export class Order {
    id: string;     //unique string generated by LB
    userInfo: ShippingInfo;
    orderCode: string;
    orderDate: Date;
    shippingFee: number;
    orderAmount: number;
    totalAmount: number;
    items: CartItem[];
    notes: string;
    paymentStatus: boolean;

    constructor(values: Object = {}){
        Object.assign(this, values);
    }
}
